### PR TITLE
Add .jsbeautifyrc

### PR DESCRIPTION
**Pull request by FokkeZB**
- Add `.jsbeautifyrc`
- DRY `Gruntfile.js` in README
- Add Sublime Text package links

### CODE REVIEW

**Comment by ingo** [comment]
Thank you for this! I'm a little concerned about checking all these style files into the projects. In fact, I'm now taking them out and centralizing them as part of a grunt plugin: https://github.com/ingo/grunt-appc-js. Could we do something similar with a custom plugin? Alternately, how about http://editorconfig.org?

**Comment by FokkeZB** [comment]
I agree that having all these files in every project and the need to keep them up to date is not very efficient. The grunt solves it for validating the code manually or in CI, but not for live validation in editors.

Wouldn't http://editorconfig.org/ just just introduce another file instead of `.beautifyrc` with even less options. Ideally I'd want a (Sublime) editor plugin that uses the exact same .jshintrc and .jscsrc files to both live validate and even auto-format, but unfortunately such a thing doesn't seem to exist.

Idea: Could we update the grunt so that it pulls the 3 files from this repo and saves them to the project root every time it runs? That way you won't have to manually keep them up to date?

**Comment by ingo** [comment]
I thought about having the grunt plugin copy, but I'd likely not want them checked-in. My concern is that we might switch to eslint or some other solution, and then I suddenly have to update 500 repos.

With .jsbeautify, it will look up the chain of folders. What if you just made sure you checked out your projects into an "Appcelerator" folder and put a .jsbeautify at the root? "The plugin looks for a .jsbeautifyrc file in the same directory as the source file you're prettifying (or any directory above if it doesn't exist, or in your home folder if everything else fails) and uses those options along the default ones. Here's an example of how it can look like."

I'd like to effectively separate IDE configuration from formatting configuration, though for things like Java, it's effectively the same.

**Comment by FokkeZB** [comment]
Yes, that's a good idea.

**Comment by FokkeZB** [comment]
Closing for inactivity

**Pull request closed without merging**
